
trigger:
- none

pool:
  vmImage: 'macos-latest'

variables:
  ProfileFileName: 'My_Range_BC.mobileprovision'
  ProfileUUID: 'efb503e7-d542-44f3-bef5-4c43e21248bf'
  CertificateFileName: 'itunes-store.p12'
  WorkspacePath: '**/Myra.xcworkspace'
  SchemaName: 'Myra'
  ExportOptionsFileName: 'options.plist'
  ExportMethod: 'app-store'
  # Variables below are used for ITC uploads
  BundleID: 'ca.bc.gov.myrangebc'
  AppStoreServiceConnectionName: 'BCDevX'
  ITCTeamID: 908186

steps:



- task: CocoaPods@0
  timeoutInMinutes: 5
  inputs:
    forceRepoUpdate: false
- task: Xcode@5
  displayName: Build
  timeoutInMinutes: 15
  inputs:
    actions: 'archive'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '$(WorkspacePath)'
    scheme: '$(SchemaName)'
    packageApp: false
    signingOption: 'default'
    args: '-xcconfig release.xcconfig'

