
trigger:
- none

pool:
  vmImage: 'macos-latest'

variables:
  ProfileFileName: 'My_Range_BC.mobileprovision'
  ProfileUUID: 'efb503e7-d542-44f3-bef5-4c43e21248bf'
  CertificateFileName: 'itunes-store.p12'
  WorkspacePath: '**/Myra.xcworkspace'
  SchemaName: 'Myra'
  ExportOptionsFileName: 'options.plist'
  ExportMethod: 'app-store'
  # Variables below are used for ITC uploads
  BundleID: 'ca.bc.gov.myrangebc'
  AppStoreServiceConnectionName: 'BCDevX'
  ITCTeamID: 908186

steps:


- task: CmdLine@2
  displayName: Bump build number
  timeoutInMinutes: 1
  inputs:
    script: |
        ./scripts/az-set-build-no.sh $(SchemaName) # SchemaName matches the target.
- task: CocoaPods@0
  timeoutInMinutes: 5
  inputs:
    forceRepoUpdate: false
- task: Xcode@5
  displayName: Build
  timeoutInMinutes: 15
  inputs:
    actions: 'archive' # build, clean, test, analyze, and archive
    scheme: $(SchemaName)
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: $(WorkspacePath)
    xcodeVersion: 'default'
    packageApp: true
    signingOption: 'default'
    provisioningProfileUuid: $(ProfileUUID)
    exportMethod: $(ExportMethod)
    exportOptions: 'plist'
    exportOptionsPlist: $(ExportOptionsFileName)
    archivePath: '$(Build.ArtifactStagingDirectory)/pack'
    args: '-xcconfig release.xcconfig'

